
# This file was *autogenerated* from the file franklin_reiter_related_message.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
import sys

n = int(sys.argv[_sage_const_1 ])
e = int(sys.argv[_sage_const_2 ])
c1 = int(sys.argv[_sage_const_3 ])
c2 = int(sys.argv[_sage_const_4 ])
r = int(sys.argv[_sage_const_5 ])
a = int(sys.argv[_sage_const_6 ])

R = Zmod(n)['X']; (X,) = R._first_ngens(1)
f1 = X**e - c1
f2 = (a*X + r)**e - c2

def fun_gcd(a, b):
    if a == _sage_const_0 : return b
    if b == _sage_const_0 : return a
    # print("Dimensionality reduction : ")
    while b:
        # print(str(a.degree()))
        a, b = b, a % b
    return a.monic()

print(-fun_gcd(f1, f2).coefficients()[_sage_const_0 ])

